import { FilterConfig } from '@/components/filters/FilterPanel';

// Фильтры для недвижимости
export const propertyFilters: FilterConfig[] = [
  {
    id: 'priceRange',
    type: 'range',
    label: 'Цена',
    min: 0,
    max: 500000,
    step: 10000,
  },
  {
    id: 'location',
    type: 'select',
    label: 'Локация',
    options: [
      { value: 'santa_cruz', label: 'Санта-Круз' },
      { value: 'los_cristianos', label: 'Лос-Кристианос' },
      { value: 'costa_adeje', label: 'Коста-Адехе' },
      { value: 'playa_americas', label: 'Плайя-де-лас-Америкас' },
      { value: 'puerto_cruz', label: 'Пуэрто-де-ла-Круз' },
      { value: 'candelaria', label: 'Канделария' },
      { value: 'los_gigantes', label: 'Лос-Хигантес' },
    ],
  },
  {
    id: 'propertyType',
    type: 'select',
    label: 'Тип недвижимости',
    options: [
      { value: 'apartment', label: 'Квартира' },
      { value: 'house', label: 'Дом' },
      { value: 'villa', label: 'Вилла' },
      { value: 'penthouse', label: 'Пентхаус' },
      { value: 'studio', label: 'Студия' },
      { value: 'commercial', label: 'Коммерческая' },
      { value: 'land', label: 'Участок' },
    ],
  },
  {
    id: 'bedrooms',
    type: 'select',
    label: 'Количество комнат',
    options: [
      { value: '0', label: 'Студия' },
      { value: '1', label: '1 комната' },
      { value: '2', label: '2 комнаты' },
      { value: '3', label: '3 комнаты' },
      { value: '4', label: '4 комнаты' },
      { value: '5+', label: '5+ комнат' },
    ],
  },
  {
    id: 'area',
    type: 'range',
    label: 'Площадь (м²)',
    min: 20,
    max: 500,
    step: 10,
  },
  {
    id: 'floor',
    type: 'range',
    label: 'Этаж',
    min: 0,
    max: 20,
    step: 1,
  },
  {
    id: 'yearBuilt',
    type: 'range',
    label: 'Год постройки',
    min: 1950,
    max: 2025,
    step: 1,
  },
  {
    id: 'condition',
    type: 'select',
    label: 'Состояние',
    options: [
      { value: 'needs_renovation', label: 'Требует ремонта' },
      { value: 'good', label: 'Готово к проживанию' },
      { value: 'excellent', label: 'Отличное' },
      { value: 'new', label: 'Новое' },
    ],
  },
  {
    id: 'balcony',
    type: 'select',
    label: 'Балкон/Терраса',
    options: [
      { value: 'balcony', label: 'Балкон' },
      { value: 'terrace', label: 'Терраса' },
      { value: 'garden', label: 'Сад' },
    ],
  },
  {
    id: 'parking',
    type: 'select',
    label: 'Парковка',
    options: [
      { value: 'garage', label: 'Гараж' },
      { value: 'parking_space', label: 'Парковочное место' },
      { value: 'street', label: 'Уличная парковка' },
    ],
  },
  {
    id: 'furnished',
    type: 'select',
    label: 'Меблировка',
    options: [
      { value: 'yes', label: 'Да' },
      { value: 'no', label: 'Нет' },
      { value: 'partial', label: 'Частично' },
    ],
  },
];

// Фильтры для автомобилей
export const carFilters: FilterConfig[] = [
  {
    id: 'priceRange',
    type: 'range',
    label: 'Цена (за день)',
    min: 0,
    max: 200,
    step: 5,
  },
  {
    id: 'make',
    type: 'select',
    label: 'Марка',
    options: [
      { value: 'toyota', label: 'Toyota' },
      { value: 'volkswagen', label: 'Volkswagen' },
      { value: 'renault', label: 'Renault' },
      { value: 'seat', label: 'Seat' },
      { value: 'opel', label: 'Opel' },
      { value: 'mercedes', label: 'Mercedes-Benz' },
      { value: 'bmw', label: 'BMW' },
      { value: 'audi', label: 'Audi' },
      { value: 'mini', label: 'Mini' },
      { value: 'mazda', label: 'Mazda' },
      { value: 'nissan', label: 'Nissan' },
      { value: 'fiat', label: 'Fiat' },
      { value: 'kia', label: 'Kia' },
      { value: 'dacia', label: 'Dacia' },
    ],
  },
  {
    id: 'year',
    type: 'range',
    label: 'Год выпуска',
    min: 2015,
    max: 2025,
    step: 1,
  },
  {
    id: 'mileage',
    type: 'range',
    label: 'Пробег (км)',
    min: 0,
    max: 200000,
    step: 10000,
  },
  {
    id: 'fuel',
    type: 'select',
    label: 'Тип топлива',
    options: [
      { value: 'petrol', label: 'Бензин' },
      { value: 'diesel', label: 'Дизель' },
      { value: 'hybrid', label: 'Гибрид' },
      { value: 'electric', label: 'Электрический' },
      { value: 'lpg', label: 'Газ' },
    ],
  },
  {
    id: 'transmission',
    type: 'select',
    label: 'Коробка передач',
    options: [
      { value: 'manual', label: 'Механическая' },
      { value: 'automatic', label: 'Автоматическая' },
      { value: 'semi-automatic', label: 'Полуавтоматическая' },
    ],
  },
  {
    id: 'bodyType',
    type: 'select',
    label: 'Тип кузова',
    options: [
      { value: 'sedan', label: 'Седан' },
      { value: 'hatchback', label: 'Хэтчбек' },
      { value: 'suv', label: 'Внедорожник' },
      { value: 'van', label: 'Фургон' },
      { value: 'coupe', label: 'Купе' },
      { value: 'convertible', label: 'Кабриолет' },
      { value: 'wagon', label: 'Универсал' },
    ],
  },
  {
    id: 'seats',
    type: 'select',
    label: 'Количество мест',
    options: [
      { value: '2', label: '2 места' },
      { value: '4', label: '4 места' },
      { value: '5', label: '5 мест' },
      { value: '7', label: '7 мест' },
      { value: '9', label: '9 мест' },
    ],
  },
  {
    id: 'doors',
    type: 'select',
    label: 'Количество дверей',
    options: [
      { value: '3', label: '3 двери' },
      { value: '5', label: '5 дверей' },
    ],
  },
  {
    id: 'features',
    type: 'multiSelect',
    label: 'Дополнительные опции',
    options: [
      { value: 'air_conditioning', label: 'Кондиционер' },
      { value: 'backup_camera', label: 'Камера заднего вида' },
      { value: 'multimedia', label: 'Мультимедийная система' },
      { value: 'navigation', label: 'Навигация' },
      { value: 'bluetooth', label: 'Bluetooth' },
      { value: 'cruise_control', label: 'Круиз-контроль' },
      { value: 'parking_sensors', label: 'Парктроник' },
    ],
  },
];

// Фильтры для экскурсий
export const excursionFilters: FilterConfig[] = [
  {
    id: 'priceRange',
    type: 'range',
    label: 'Цена',
    min: 0,
    max: 200,
    step: 5,
  },
  {
    id: 'location',
    type: 'select',
    label: 'Локация',
    options: [
      { value: 'teide', label: 'Тейде' },
      { value: 'anaga', label: 'Анага' },
      { value: 'masca', label: 'Маска' },
      { value: 'los_gigantes', label: 'Лос-Хигантес' },
      { value: 'santa_cruz', label: 'Санта-Круз' },
      { value: 'puerto_cruz', label: 'Пуэрто-де-ла-Круз' },
      { value: 'la_gomera', label: 'Ла-Гомера' },
    ],
  },
  {
    id: 'category',
    type: 'select',
    label: 'Тип развлечения',
    options: [
      { value: 'boat_trip', label: 'Прогулка на катере' },
      { value: 'hiking', label: 'Пешая экскурсия' },
      { value: 'jeep_safari', label: 'Джип-сафари' },
      { value: 'museum', label: 'Музей' },
      { value: 'aquapark', label: 'Аквапарк' },
      { value: 'cultural', label: 'Культурная' },
      { value: 'nature', label: 'Природная' },
      { value: 'adventure', label: 'Приключенческая' },
      { value: 'family', label: 'Семейная' },
    ],
  },
  {
    id: 'duration',
    type: 'select',
    label: 'Продолжительность',
    options: [
      { value: '1-3h', label: '1-3 часа' },
      { value: '4-6h', label: '4-6 часов' },
      { value: '7-8h', label: '7-8 часов' },
      { value: 'full_day', label: 'Полный день' },
      { value: 'multi_day', label: 'Несколько дней' },
    ],
  },
  {
    id: 'difficulty',
    type: 'select',
    label: 'Уровень сложности',
    options: [
      { value: 'easy', label: 'Легкий' },
      { value: 'moderate', label: 'Средний' },
      { value: 'hard', label: 'Сложный' },
    ],
  },
  {
    id: 'groupSize',
    type: 'select',
    label: 'Размер группы',
    options: [
      { value: 'individual', label: 'Индивидуально' },
      { value: 'small', label: 'Малая группа (до 8 чел.)' },
      { value: 'medium', label: 'Средняя группа (до 15 чел.)' },
      { value: 'large', label: 'Большая группа (до 30 чел.)' },
    ],
  },
  {
    id: 'guideLanguage',
    type: 'select',
    label: 'Язык гида',
    options: [
      { value: 'ru', label: 'Русский' },
      { value: 'en', label: 'Английский' },
      { value: 'es', label: 'Испанский' },
      { value: 'de', label: 'Немецкий' },
      { value: 'fr', label: 'Французский' },
      { value: 'pl', label: 'Польский' },
    ],
  },
  {
    id: 'suitableFor',
    type: 'multiSelect',
    label: 'Подходит для',
    options: [
      { value: 'children', label: 'Детей' },
      { value: 'families', label: 'Семей' },
      { value: 'couples', label: 'Пар' },
      { value: 'seniors', label: 'Пожилых' },
      { value: 'extreme', label: 'Любителей экстрима' },
    ],
  },
  {
    id: 'includes',
    type: 'multiSelect',
    label: 'Включено',
    options: [
      { value: 'transport', label: 'Транспорт' },
      { value: 'food', label: 'Питание' },
      { value: 'tickets', label: 'Билеты' },
      { value: 'guide', label: 'Гид' },
      { value: 'equipment', label: 'Оборудование' },
    ],
  },
  {
    id: 'minAge',
    type: 'range',
    label: 'Минимальный возраст',
    min: 0,
    max: 18,
    step: 1,
  },
];